"""本機 GUI renderer 的相容匯出入口。"""

from __future__ import annotations

from app.web.ui_components import (
    action_row,
    button_style,
    card,
    data_table,
    empty_state_card,
    flash_message,
    form_card,
    link_button,
    notice_box,
    page_layout,
    submit_button,
    table_cell,
    table_row,
    text_link,
    unsaved_changes_indicator,
    unsaved_changes_script,
)
from app.web.ui_styles import (
    ACTION_ROW_STYLE,
    BODY_STYLE,
    CARD_STYLE,
    ERROR_STYLE,
    SUCCESS_STYLE,
    TABLE_STYLE,
    cell_style,
    danger_button_style,
    disabled_button_style,
    input_style,
    pre_style,
    primary_button_style,
    secondary_button_style,
)
from app.web.view_formatters import format_datetime_for_display

__all__ = [
    "ACTION_ROW_STYLE",
    "BODY_STYLE",
    "CARD_STYLE",
    "ERROR_STYLE",
    "SUCCESS_STYLE",
    "TABLE_STYLE",
    "action_row",
    "button_style",
    "card",
    "cell_style",
    "danger_button_style",
    "data_table",
    "disabled_button_style",
    "empty_state_card",
    "flash_message",
    "format_datetime_for_display",
    "form_card",
    "input_style",
    "link_button",
    "notice_box",
    "page_layout",
    "pre_style",
    "primary_button_style",
    "secondary_button_style",
    "submit_button",
    "table_cell",
    "table_row",
    "text_link",
    "unsaved_changes_indicator",
    "unsaved_changes_script",
]
